name: Copy File on Commit

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: nayanamadhusoodanan/QA_Changes1
          token: ${{ secrets.GITHUB_TOKEN }}

      # Copy the file to a destination directory within the GitHub Actions runner
      - name: Copy test.py to destination
        run: |
          mkdir -p ~/Desktop
          cp nayanamadhusoodanan/QA_Changes1/src/test.py ~/Desktop/test.py
