name: Copy File on Commit

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: nayanamadhusoodanan/QA_Changes1
          token: ${{ secrets.GITHUB_TOKEN }}
     # Debugging step: List files in the src directory
      - name: List files in src directory
        run: ls -R src
     # Debugging step: List files in the destination directory
      - name: List files in src directory
        run: ls -R destination  
        
      # Copy the file to a destination directory within the GitHub Actions runner
      - name: Copy test.py to destination
        run: |
          mkdir -p destination/
          cp src/tests/test.py destination/
      
      - name: Upload test.py as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backup-test-py
          path: ~/Desktop/test.py    
