jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Store files in a specific location
      - name: Copy specific files
        run: |
          mkdir -p C:\Users\nayana.m\Desktop
          cp -R path/to/your/files/* C:\Users\nayana.m\Desktop
