name: Sync QA-Changes1 to QA-Changes2

on:
  push:
    branches:
      - main  # or the branch you want to watch for changes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout QA-Changes1
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync changes to QA-Changes2
      env:
        REPO2: nayanam-ext-eightfold/QA_Changes2  # replace with repo2 details 
        REPO2_TOKEN: ${{ secrets.SECRET1 }}  # Personal Access Token for repo2
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

        # Clone repo2
        git clone https://x-access-token:${REPO2_TOKEN}@github.com/${REPO2}.git
        cd nayanam-ext-eightfold/QA-Changes2

        # Copy changes from repo1 to repo2
        cp -r ../QA-Changes1/* .

        # Commit and push changes
        git add .
        git commit -m "Sync changes from repo1"
        git push origin main  # or the branch you want to push to in repo2
